# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build status

on:
  push:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      if: false
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev --ignore-pipfile --deploy
    - name: Run tests
      if: false
      run: |
        pipenv run pytest
    - name: Convert notebook
      if: true
      run: |
        pipenv run jupyter nbconvert final_project.ipynb --to html --output html/index.html
    - name: Make docs
      if: false
      run: |
        pipenv run make html
    - name: Deploy docs to gh-pages
      if: true
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages
        folder: html
